---
- name: nginx-proxy | Write static pod
  template:
    src: manifests/nginx-proxy.manifest.j2
    dest: "{{kube_manifest_dir}}/nginx-proxy.yml"

- name: nginx-proxy | Make nginx directory
  file:
    path: "{{ custom_nginx_proxy_path|default(nginx_proxy_path) }}"
    state: directory
    mode: 0700
    owner: root

- name: nginx-proxy | Write nginx-proxy configuration
  template:
    src: nginx.conf.j2
    dest: "{{ custom_nginx_proxy_path|default(nginx_proxy_path) }}/nginx.conf"
    owner: root
    mode: 0755
    backup: yes
